// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqumadfvpnjkomiqixiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxdW1hZGZ2cG5qa29taXFpeGl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjUxODgsImV4cCI6MjA2NTUwMTE4OH0.ix9E79dNxvE5rTYXPwUoRwyvtYHILIK2aAz6a8yd8zI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);